# /usr/local/etc/doas.conf
# Replace 'yourusername' with your actual username

permit persist :wheel
permit nopass :wheel cmd pkg
permit nopass :wheel cmd shutdown
permit nopass :wheel cmd reboot
permit nopass :wheel cmd sysctl
